
builds:
  -
    id: v8imanager
    binary: v8imanager
    main: ./cmd/windowsservice
    archives:

    goarch:
      - amd64
    goos:
      - windows
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w
      - -s
      - -X main.Version={{.Tag}}
archives:
  -
    id: 'v8imanager'
    builds: ['v8imanager']
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE