archives:
  - format_overrides:
      - goos: windows
        format: zip
builds:
  - binary: v8imanager
    main: ./cmd/windowsservice
    archives:

    goarch:
      - amd64
    goos:
      - windows
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w
      - -s
      - -X main.Version={{.Tag}}